version: '3.8'

services:
  django:
    build:
      context: ./
      dockerfile: ./compose/local/Dockerfile
    entrypoint: bash start-project.sh
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    env_file:
      - ./compose/.env/.env.local
    expose:
      - 8000
    depends_on:
      - postgresql
      - redis
  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: application_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
  redis:
    image: redis:alpine 
    expose:
      - 6379
  caddy:
    image: caddy:alpine 
    ports:
      - 80:80
      - 443:443 
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/cdata
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    depends_on:
      - django
  mailhog:
    image: mailhog/mailhog:latest
    expose:
      - 1025
      - 8025
      
volumes:
  postgres_data:
  static:
  media:
  caddy_data:
